---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  sqlite3
  database: db/chef_development.sqlite3

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgresql
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  <<:       *defaults
  database: chef_test

  # repositories:
  #   repo1:
  #     database: sample_development

production:
  <<:       *defaults
  database: chef_production

  # repositories:
  #   repo1:
  #     database: sample_development
